/* Copyright (c) 2023 TORITI LIMITED 2022 */

module.exports = {
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  API_FAILED: 'API_FAILED',
  MISSING_AUTHORITY: 'MISSING_AUTHORITY', //không có quyền
  POPULAR_ERROR: {
    INSERT_FAILED: 'INSERT_FAILED',
    RECORD_NOT_FOUND: 'RECORD_NOT_FOUND',
    UPDATE_FAILED: 'UPDATE_FAILED',
    DELETE_FAILED: 'DELETE_FAILED',
  },
};
