/* Copyright (c) 2022 TORITI LIMITED 2022 */

/**
 * Created by A on 7/18/17.
 */
'use strict';

const { CronInstance, executeJob } = require('../ThirdParty/Cronjob/CronInstance');
const Logger = require('../utils/logging');

const CustomerRecordJob = require('../API/CustomerRecord/cronjob/StationsRecordAutoCheck');
const CustomerMessageJob = require('../API/CustomerMessage/cronjob/StationsMessageAutoSend');
const AutoSendMessageToMail = require('../API/CustomerMessage/cronjob/CustomerMessageEmailJob');

async function startSchedule() {
  Logger.info('startSchedule ', new Date());

  //do not run schedule on DEV environments
  if (process.env.NODE_ENV === 'dev') {
    return;
  }

  // every one hour
  const CustomerRecordAutoDeleteJob = require('../API/CustomerSchedule/cronjob/AutoDeleteCustomerRecord');
  setInterval(CustomerRecordAutoDeleteJob.autoDeleteCustomerRecord, 60 * 60 * 1000);

  //every 2 minutes
  // const CustomerMessageJob = require('../API/CustomerMessage/cronjob/StationsMessageAutoSend');
  // setInterval(CustomerMessageJob.autoSendMessageForCustomer, 2 * 60 * 1000);

  //every 1 minutes
  const CustomerMessagePushNotificationJob = require('../API/CustomerMessage/cronjob/CustomerMessagePushNotificationJob');
  setInterval(CustomerMessagePushNotificationJob.sendFCMToAllCustomer, 1 * 60 * 1000);

  //every 30 seconds
  // const CustomerRecordJob = require('../API/CustomerRecord/cronjob/StationsRecordAutoCheck');
  // setInterval(CustomerRecordJob.autoUpdateProcessForStation, 30 * 1000);

  //every 5 minute
  // const { updateStatusForSendingSMS } = require('../API/CustomerMessage/cronjob/ScriptUpdateStatusSMS');
  // setInterval(updateStatusForSendingSMS, 5 * 60 * 1000);

  //** Job mỗi ngày - Code ở đây nên sắp xếp theo trình tự thời gian để dễ kiểm soát */
  // Mỗi ngày tự động thông báo nhắc lịch hẹn vào lúc 7:00
  CronInstance.schedule('0 7 * * *', async function () {
    executeJob('./API/CustomerSchedule/cronjob/AutoNotifyScheduleJob.js');
  });

  // Mỗi ngày vào chủ nhật sẽ thông báo nhắc nhở khách hàng cập nhật thông tin phương tiện sau khi đăng kiểm thành công
  CronInstance.schedule('0 8 * * 0', async function () {
    executeJob('./API/AppUserVehicle/cronjob/NotifyUpdateVehicleInfoJob.js');
  });

  // Mỗi ngày chuyển các account user đã xóa vào bảng mới và xóa luôn dòng record đó.
  CronInstance.schedule('0 10 * * 0', async function () {
    executeJob('./API/AppUsers/cronjob/autoMoveDeletedAccountJob.js');
  });

  // Mỗi ngày tự động tra cứu phạt nguội cho các phương tiện đã đăng ký
  CronInstance.schedule('0 20 * * *', async function () {
    executeJob('../API/AppUserVehicle/cronjob/CheckingCustomerCrimeJob.js');
  });

  // Mỗi ngày tự động hoàn tất các lich hẹn xác nhận vào lúc 20:00
  CronInstance.schedule('0 20 * * *', async function () {
    executeJob('./API/CustomerSchedule/cronjob/AutoCompleteScheduleJob.js');
  });

  // Mỗi ngày tự động hoàn tất các lượt đăng kiểm chưa xử lý vào lúc 20:00
  CronInstance.schedule('0 20 * * *', async function () {
    executeJob('./API/CustomerRecord/cronjob/StationsRecordCompleteJob.js');
  });

  // Mỗi ngày tự tạo report cho các trạm vào lúc 21:00
  CronInstance.schedule('0 21 * * *', async function () {
    executeJob('./API/StationReport/cronjob/AutoGenerateDailyReport.js');
  });

  // Mỗi ngày tự tạo lịch nghỉ cho các trạm vào lúc 22:00
  CronInstance.schedule('0 22 * * *', async function () {
    executeJob('./API/StationWorkSchedule/cronjob/AutoCreateDayOffJob.js');
  });

  // Mỗi ngày xóa các record tin nhắn SMS hết hạn
  CronInstance.schedule('0 22 * * 0', async function () {
    executeJob('./API/SMSMessage/cronjob/deleteExpiredSMSJob.js');
  });

  // Mỗi ngày tự tạo thông báo trạng thái hoạt động của trạm
  CronInstance.schedule('0 23 * * *', async function () {
    executeJob('./API/AppUsers/cronjob/autoNotifyStatusActiveJob.js');
  });

  // Mỗi ngày xóa các tài khoản chưa kích hoạt quá 60 ngày
  CronInstance.schedule('0 23 * * 0', async function () {
    executeJob('./API/AppUsers/cronjob/autoDeleteInactiveUserJob.js');
  });

  // Mỗi ngày chuyển dữ liệu đăng kiểm đã xóa sang bảng CustomerRecordDeleted
  CronInstance.schedule('0 23 * * 0', async function () {
    executeJob('./API/CustomerRecord/cronjob/saveDeletedRecordJob.js');
  });

  // Mỗi ngày chuyển dữ liệu phương tiện đã xóa sang bảng AppUserVehicleDeleted
  CronInstance.schedule('0 23 * * 0', async function () {
    executeJob('./API/AppUserVehicle/cronjob/AutoMoveDeletedVehicleJob.js');
  });

  // Mỗi ngày chuyển dữ liệu mesage của user đã xóa tài khoản sang bảng MessageCustomerDeleted
  CronInstance.schedule('0 23 * * 0', async function () {
    executeJob('./API/CustomerMessage/cronjob/AutoMoveMessageJob.js');
  });

  // Mỗi ngày tự gửi tổng kết báo cáo lúc 7h đến các lãnh đạo
  CronInstance.schedule('0 7 * * *', async function () {
    executeJob('./API/CustomerStatistical/cronjob/autoSendReportDataJob');
  });
}

module.exports = {
  startSchedule,
};
